version: "3.1"

services:

  api:
    image: api
    build: ./api
    working_dir: /var/www/
    volumes:
      - ./api:/var/www/
      - ./api/public/:/var/www/html/
    ports:
      - 8200:80
    environment:
      - POSTGRES_NAME=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
      
  db:
    image: pgrouting/pgrouting:latest
    env_file: .env
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432